[workspace]
resolver = "2"
members = [
    "crates/kernel",
    "crates/klib",
    "crates/mm",
    "crates/arch/arch",
    "crates/arch/arch-x86_64",
    "crates/drv",
    "crates/vfs",
    "crates/task",
    "crates/ipc",
    "crates/loader",
    "crates/term",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
