[package]
name = "kernel"
version.workspace = true
edition.workspace = true

[build-dependencies]

[dependencies]
limine = { version = "0.1", features = ["requests-section"] }
flanterm_rust = { path = "../../vendor/flanterm_rust" }
klib = { path = "../klib" }
drv = { path = "../drv" }
arch = { path = "../arch/arch" }
arch-x86_64 = { path = "../arch/arch-x86_64" }
mm = { path = "../mm" }
